"""
Configuration parameters for the evolution simulation.
"""

# General simulation parameters
GRID_SIZE = 100
RANDOM_SEED = None  # Set to an integer for reproducible results

# Abiogenesis parameters
ABIOGENESIS_MAX_ITER = 10000
CHEMICAL_COMPLEXITY_THRESHOLD = 10
CHEMICAL_MUTATION_RATE = 0.001
CHEMICAL_MUTATION_STEP = 1

# Cellular parameters
INITIAL_CELLS = 10
CELL_INITIAL_ENERGY = 20
CELL_INITIAL_DNA_COMPLEXITY = 10
CELL_FRICTION = 0.9
CELL_METABOLIC_COST = 1.0
CELL_REPLICATION_THRESHOLD = 30
CELL_REPLICATION_AGE = 5
CELL_MAX_AGE = 100

# Nutrient and diffusion parameters
NUTRIENT_INITIAL_VALUE = 5.0
NUTRIENT_REGENERATION_RATE = 0.2
NUTRIENT_CONSUMPTION_MAX = 0.8

# Multicellular parameters
MULTICELL_MOVEMENT_SCALE = 0.05
MULTICELL_ENERGY_THRESHOLD = 150
MULTICELL_REPLICATION_AGE = 10
MULTICELL_MAX_AGE = 200

# Intelligence parameters
NN_INPUT_SIZE = 6
NN_HIDDEN1_SIZE = 12
NN_HIDDEN2_SIZE = 8
NN_OUTPUT_SIZE = 3
NN_MUTATION_RATE = 0.05
INTELLIGENCE_ENERGY_THRESHOLD = 250
INTELLIGENCE_ENERGY_COST = 1
INTELLIGENCE_MAX_FRAMES = 300